### ISSUE TITLE
load_wrapper should not fail for ObsSims with -15V supply

### ISSUE THREAD

**Issue by ebokhour** [TESScience/tessfpe#12]
Currently, load_wrapper fails if it finds supply voltages out of range (unit_tests fails).  Since some ObsSim units have -12V supplies, and some have -15V supplies, this will prevent load_wrapper from completing for some ObsSim setups.

It would be better if load_wrapper simply reported the -15V supply, but otherwise completed normally.

**Comment by xcthulhu** [comment]
Fixed as of tagged release [6.2.4](https://github.com/TESScience/tessfpe/releases/tag/6.2.4)
