### ISSUE TITLE
scan_plots should only output the summary.pdf

### ISSUE THREAD

**Issue by ebokhour** [TESScience/tessfpe#13]
Currently scan_plots creates a set of 26 pdfs in the tmp/ directory, along with a summary PDF including all 26.  It will be much more convenient if scan_plots outputs only the summary PDF, and puts it in the directory from which scan_plots is called.

**Comment by xcthulhu** [comment]
By default, it dumps the summary to a uniquely named temporarly file in /tmp

`scan_plots` takes an optional second argument if you wish to specify a particular file you wish to output the summary to.
