### ISSUE TITLE
testsuite/tessfpe

### ISSUE THREAD

**Issue by noqsi** [TESScience/tessfpe#17]
From "make install_testsuite" in a virgin clone, something creates this and then "make venv" chokes on it.

**Comment by noqsi** [comment]
Something like "cd testsuite; rm -rf tessfpe; make venv" seems to be the work-around.

**Comment by jimlittlefield** [comment]
On Cosmos the install issue(s) were caused by ..

a)  Missing virtual-env package
b)  Missing lib-png
c)  Missing freetype package

Issues were caused by the Centos 6->7 upgrade which seemed to remove used packages.

**Comment by xcthulhu** [comment]
@jimlittlefield : Try following these install instructions

https://github.com/TESScience/tessfpe/wiki/CLI-tessfpe-Documentation#development-installation
