### ISSUE TITLE
load wrapper hangs

### ISSUE THREAD

**Issue by jsvilla** [TESScience/tessfpe#18]
When load wrapper is used for the first time on tessgse3 using FPE2, it hangs. Output is shown below, using the --debug option. Note that the port number on the tftp command line (70) is different from what was successfully used before on this setup (69).

tessgse3.mit.edu% load_wrapper --FPE-number 2 --debug
FPE2>  cam_control
cam_control = 0x00000000
cam_control
FPE2>  cam_control = 0x00000000
cam_control
FPE2>  cam_control = 0x00000000
cam_control
FPE2>  cam_control = 0x00000000
cam_control
FPE2>  cam_control = 0x00000000
cam_hsk
FPE2>  cam_control
cam_control
cam_control
cam_control
cam_control
Timeout
FPE2>  cam_control
cam_control = 0x00000004
cam_control
FPE2>  cam_control = 0x00000004
camrst
FPE2>  FPE Reset complete
cam_control = 1
FPE2>  cam_control = 0x00000000
 cam_control
FPE2>  cam_control = 0x00000000
cam_control
FPE2>  cam_control = 0x00000000
camrst
FPE2>  FPE Reset complete
cam_control = 1
FPE2>  cam_control = 0x00000000
 cam_control
FPE2>  cam_control = 0x00000000
cam_fpga_rst
FPE2>  Resetting Cam FPGA
cam_control
Cam FPGA Reset done.
FPE2>  cam_control
cam_control = 0x00000000
Running:
tftp <<EOF

mode binary
connect 192.168.100.1 70
put /usr/lib/python2.7/site-packages/tessfpe/dhu/MemFiles/FPE_Wrapper-6.2.3.bin bitmem2 
EOF
cam_control
FPE2>  cam_control = 0x00000000
## CTRL-C at this point

FPE2>  cam_control
cam_control = 0x00000000
cam_control
FPE2>  cam_control = 0x00000000
Traceback (most recent call last):
 File "/usr/bin/load_wrapper", line 45, in <module>
   dhu_reset=args.dhu_reset))
 File "/usr/lib/python2.7/site-packages/tessfpe/dhu/fpe.py", line 138, in load_wrapper
   self.upload_fpe_wrapper_bin(fpe_wrapper_binary)
 File "/usr/lib/python2.7/site-packages/tessfpe/dhu/fpe.py", line 415, in upload_fpe_wrapper_bin
   "bitmem" + str(self.fpe_number))
 File "/usr/lib/python2.7/site-packages/tessfpe/dhu/fpe.py", line 197, in tftp_put
   self.connection.wait_for_pattern(r'.*Load complete\n\r')
 File "/usr/lib/python2.7/site-packages/tessfpe/dhu/fpesocketconnection.py", line 85, in wait_for_pattern
   data = str(self.socket.recv(chars)).encode()
KeyboardInterrupt

**Comment by TESSUser** [comment]
Joel,
The correct use of the command is 
load_wrapper 6.2.4 --FPE-number 2

You were missing the FPGA version number.  I think your installation should have 6.2.4.  If not, try 6.2.3.

EdB

---

Ed Bokhour
ebok@alum.mit.edu

**Comment by jsvilla** [comment]
Ed,

I think that one of the wrappers (6.2.3?) is a default. In any case, we also tried that command as you said, and it also produced the same error message. The tftp port number for FPE2 should be changed, and I believe Matt is on this.

Joel
