### ISSUE TITLE
Can't load program memory on tessgse2

### ISSUE THREAD

**Issue by ebokhour** [TESScience/tessfpe#19]
Using tessfpe 6.2.6 with ObsSim version 1.7d on tessgse2. Starting out with cam_fpga_rst and dhu_rst.

Load_wrapper 6.2.3 loads OK, but upload_fpe_program hangs.  Using the --debug feature I see that the sequencer memory seems to be loading OK but the program times out after trying to tftp the program memory.  It appears to be waiting for a pattern it never gets.

Very similar commands seem to work fine, however, on cosmos, caladan, and tessgse4, so it's also possible this is a configuration issue on tessgse2.

**Comment by xcthulhu** [comment]
This is a deployment issue, this machine is using a version of `grako` which I don't support.
