### ISSUE TITLE
Update testsuite to use 6.2.3

### ISSUE THREAD

**Issue by ebokhour** [TESScience/tessfpe#3]
Please update testsuite.sh to default to 6.1t.5.  The previous version (6.1t.4) has a bug in it which does not allow the LEDs to be turned off.

**Comment by ebokhour** [comment]
Per Kari H. this afternoon (3/14/16), 6.2.3 has been released and all 6.2 boards should use that bit file now.

**Comment by xcthulhu** [comment]
I need you to confirm this file doesn't break anything before I go ahead wit this.

**Comment by ebokhour** [comment]
6.2.3 behaves properly on my stack.  My problems with tess_obssim were resolved with power cycling of caladan.  Jerry has also verified the operation of this FPGA image in the setup at 37.

**Comment by xcthulhu** [comment]
Okay, I have made it so that this is the default wrapper that is loaded

**Comment by xcthulhu** [comment]
Spoke too soon... should be closed in next commit
