### ISSUE TITLE
Change conversion factors for driver and interface temperatures

### ISSUE THREAD

**Issue by ebokhour** [TESScience/tessfpe#8]
Need to change house_keeping conversion factors for the two signals called
driver_temperature and interface_temperature.  The conversions should be the same as for the four channels called ccd[1:4]_board_temperature, since the signals also come from REF43 chips.

**Comment by noqsi** [comment]
HeaterGroup.tsv has:

`6  Driver Temperature  360 -360                    K   
`
`7  Interface Temperature   360 -360                    K   
`
Which are the same parameters as:
`7  Board Temperature   360 -360                    K   
`
in BiasGroup.tsv. So, you should be getting similar conversions.

**Comment by ebokhour** [comment]
Here's a typical sample of what house_keeping produces for those channels:

ccd1_board_temperature  N/A          293.7892 K
ccd2_board_temperature  N/A          293.4190 K
ccd3_board_temperature  N/A          294.4270 K
ccd4_board_temperature  N/A          294.0612 K
driver_temperature            N/A          0.3713 K 
interface_temperature       N/A          0.3625 K

**Comment by noqsi** [comment]
What board revision?

On Mar 17, 2016, at 2:49 PM, Ed Bokhour notifications@github.com wrote:

> Here's a typical sample of what house_keeping produces for those channels:
> 
> ccd1_board_temperature N/A 293.7892 K
> ccd2_board_temperature N/A 293.4190 K
> ccd3_board_temperature N/A 294.4270 K
> ccd4_board_temperature N/A 294.0612 K
> driver_temperature N/A 0.3713 K
> interface_temperature N/A 0.3625 K
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub

John Doty              Noqsi Aerospace, Ltd.
http://www.noqsi.com/
jpd@noqsi.com

**Comment by ebokhour** [comment]
6.2 Interface, 6.1T driver, 6.2 video.

**Comment by noqsi** [comment]
You need a 6.2 Driver for these to read properly.

**Comment by ebokhour** [comment]
Oh, of course. I'll keep placeholder values in the list until we get some 6.2 Drivers to test. Closing this issue.
