### ISSUE TITLE
Compare house_keeping values to expected data reference sets

### ISSUE THREAD

**Issue by ebokhour** [TESScience/tessfpe#9]
The attached file is a reference set of expected housekeeping values for the case where a stack of 3 boards is assembled and an RTD/Heater Dummy Load is connected. This was based on a stack consisting of a 6.2 Interface, a 6.1T Driver, and a 6.2 Video, at room temperature, with CCD connectors open.

Reference sets (to be created by EB ) will be identified as follows:
Set A: Interface only
Set B: Interface + Driver
Set C: Interface + Driver + Video, no dummy loads attached
Set D: Interface + Driver + Video, RTD/HTR dummy load attached
Set E: Interface + Driver + Video, 4 CCD Simulators and the RTD/HTR dummy load attached

[HK_Reference_D.txt](https://github.com/TESScience/tessfpe/files/178354/HK_Reference_D.txt)

**Comment by xcthulhu** [comment]
Hey should I write these or can you?

**Comment by TESSUser** [comment]
I can write them. Was the format I used for the first one OK? Was it JSON enough?

**Comment by xcthulhu** [comment]
You can see an example expected values JSON here: https://github.com/TESScience/tessfpe/blob/master/testsuite/expected_values.json
